application: shopify-django-example
version: 1
runtime: python
api_version: 1
threadsafe: yes
runtime_config:
    python_version: 3

handlers:
- url: /static
  static_dir: static/
  expiration: '30d'

- url: /.*
  script: djangoappengine/main/main.py
  entrypoint: gunicorn -b :$PORT mydjangoapp.wsgi

#entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT
